language: go
go:
  - 1.8.1
services:
  - mysql
install:
  - go get github.com/Masterminds/glide
  - glide install
script:
  - go test $(glide novendor)
notifications:
  slack:
    rooms:
      - tnindo:UQ4e43faD5fHRZOuDEoWoF88#travis-ci
