language: go
go:
  - 1.8.1
services:
  - mysql
before_install:
  - cd $HOME/gopath/src/
  - git clone --depth=50 --branch=master https://github.com/zainul-ma/blog.git
  - cd $HOME/gopath/src/blog
install:
  - go get github.com/Masterminds/glide
  - glide install
script:
  - ls -lah
  - go env
  - pwd
  - go test $(glide novendor)
notifications:
  slack:
    rooms:
      - tnindo:UQ4e43faD5fHRZOuDEoWoF88#travis-ci
